import { AIReviewResponse, AIReviewIssue } from '../../modules/ai/ai.types';

/**
 * Formats the AI review result into a human-readable GitHub PR comment body.
 */
export function buildGithubCommentBody(reviewResult: AIReviewResponse): string {
  const severityEmoji: Record<string, string> = {
    HIGH: '🔴',
    MEDIUM: '🟡',
    LOW: '🟢',
  };

  const issueLines = reviewResult.issues
    .map((issue: AIReviewIssue, index: number) => {
      const emoji = severityEmoji[issue.severity] ?? '⚪';
      const location =
        issue.filePath
          ? `\n   > 📄 \`${issue.filePath}\`${issue.line ? ` (line ${issue.line})` : ''}`
          : '';
      return [
        `**${index + 1}. ${emoji} [${issue.severity}] [${issue.type.toUpperCase()}]** ${issue.message}`,
        location,
        `   💡 *${issue.suggestion}*`,
      ]
        .filter(Boolean)
        .join('\n');
    })
    .join('\n\n');

  return [
    '## 🤖 AI PR Review (V2)',
    '',
    '### Summary',
    reviewResult.summary,
    '',
    `### Issues Found (${reviewResult.issues.length})`,
    '',
    issueLines || '_No issues found. Great PR! 🎉_',
    '',
    '---',
    '_Generated by AI PR Reviewer - Production Ready Edition_',
  ].join('\n');
}

/**
 * Truncates a string to a given max length, appending a suffix if truncated.
 */
export function truncate(text: string, maxLength: number): string {
  if (text.length <= maxLength) return text;
  return text.slice(0, maxLength) + '\n... [truncated]';
}
